OS:=$(shell uname)
QEMU	= qemu-system-x86_64

ifeq ($(OS),Linux)
	AS		= as
	AFLAGS 	= -g --64
	LD		= ld
	LDFLAGS	= -m elf_x86_64
#	CC		= gcc
#	CFLAGS	= -g -m32 -fnobuiltin -fno-stack-protector -fomit-frame-pointer -fstrength-reduce
#	CPP		= cpp -nostdinc
#	AR		= ar
#	STRIP	= strip
	OBJCOPY	= objcopy
endif
ifeq ($(OS),Darwin)
	AS		= i386-elf-as
	AFLAGS 	= -g --64
	LD		= i386-elf-ld
	LDFLAGS	= -m elf_x86_64
	OBJCOPY = i386-elf-objcopy
endif